num = [""]

for n in num:
     num1 = float(input("Digita um  numero: "))
     num2 = float(input("Digita um  numero: "))
     num3 = float(input("Digita um  numero: "))
     num4 = float(input("Digita um  numero: "))
     num5 = float(input("Digita um  numero: "))
     num6 = float(input("Digita um  numero: "))


     soma = (num1 + num2 + num3 + num4 + num5 + num6) / 6
     print("A média é :",soma)
   


